### ISSUE TITLE
Separate functionality - Creation of stslib.py

### ISSUE THREAD

**Issue by joandrsn** [f-klubben/stregsystemet-cli#107]
Currently I'm trying to create a [rofi](https://github.com/davatorium/rofi) script for STS. In this regard, I would like to use the [`get-wares`-functionality](https://github.com/f-klubben/stregsystemet-cli/blob/6945c3b8777340dd5a419616e9c98de9f1f95dbd/main.py#L232-L252).
However this function is tightly bound to the main python file.
I suggest splitting the functionality into the following files:
- `stslib.py` - A general library containing interaction with stregsystemet. So: `test_user`, `get_wares`, `get_history`, `sale` and possibly `get_qr`
- `sts.py` - The current implemention, but calling the library instead
- `sts-strandvejen.py` - The special case of the strandvejen

And here is where I would be able to create `sts-rofi.py` which interacts with rofi.

This split does however come with a drawback: The update script needs to support updating multiple files.

Currently it is only a suggestion. I don't know if there is even any support a change like this.

**Comment by falkecarlsen** [comment]
:+1:

**Comment by Zaph-x** [comment]
This issue has been implemented in #117, where STS was updated to V2, which includes classes and classtypes for STS.
With this, it is possible to simply import the sts main file as a library, and use the classes.

STS python android app when?
