### ISSUE TITLE
CTRL+D should not throw EOFError

### ISSUE THREAD

**Issue by SEbbaDK** [f-klubben/stregsystemet-cli#46]
`ctrl+d` in most shells issue an EOF character, which is a relatively universal way of ending a shell or other text input (like the buy menu in `sts`).
We should just gracefully handle this character and exit.

```
Id> Traceback (most recent call last):
File "/bin/sts", line 416, in <module>
    main()
File "/bin/sts", line 400, in main
    user_buy(args.user)
File "/bin/sts", line 294, in user_buy
    item, count = get_item([x[0] for x in wares])
File "/bin/sts", line 260, in get_item
    item_id = input('Id> ')
    
EOFError
```

**Comment by Zaph-x** [comment]
Definitely agree on this one! Same goes for KeyboardInterrupt error
