### ISSUE TITLE
Plugin help message suggestion does not work

### ISSUE THREAD

**Issue by falkecarlsen** [f-klubben/stregsystemet-cli#80]
STS writes the following when 'plugin_dir' is not set:
`STS now supports plugins. Add "plugin_dir=~/.sts_plugins/" to your .sts file`

However, (on my system at least) the expansion of home (~) does not work and I have to give it a FQN (`/home/$user/.config/sts/plugins/etc`).

Having some way to supress the "heyo, we got plugins" message without having to _setup_ plugins would be nice, since you can know of the support but choose not to use it.

**Comment by Zaph-x** [comment]
Fixed in #84
