### ISSUE TITLE
Whenever one buys something the Stregsystem should display the first gif found when searching the inputted username.

### ISSUE THREAD

**Issue by RasmusHoeyerHansen** [f-klubben/stregsystemet-cli#85]

**Comment by RasmusHoeyerHansen** [comment]
Use Tenor or similar. I am sure you monkeys can find an existing API.

**Comment by Zaph-x** [comment]
> Use Tenor or similar. I am sure you monkeys can find an existing API.

This is a CLI tool, that runs in the terminal. As such there is no support for images. I refer you to https://github.com/f-klubben/stregsystemet/issues/new
